/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("----------gates.js-----------");
        jSLinter("./src/main/resources/gates.js");
        System.out.println("----------gates-no-errors.js-----------");
        jSLinter("./src/main/resources/gates-no-errors.js");
        System.out.println("----------gates-1-error.js-----------");
        jSLinter("./src/main/resources/gates-1-error.js");
        System.out.println("-----------gates-no-errors.js----------");
        jSLinter("./src/main/resources/gates-no-errors.js");


    }

    public static void jSLinter(String path) {
        Scanner s = null;
        int lineCounter = 0;
        String line = null;
        try {
            s = new Scanner(new BufferedReader(new FileReader((path))));
            while (s.hasNextLine()) {
                lineCounter++;
                line = s.nextLine();
//                System.out.println(line);
                if (!line.contains(";")) {
                    if (!line.contains("{") && !(line.contains("}") || line.length() == 0)) {
                        System.out.println("Line " + lineCounter + ": Missing semicolon.");
                    }
                }
            }
        } catch (FileNotFoundException e) {
            System.out.println("Unable to find file");
        }
    }
}
