/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", Library.someLibraryMethod());
    }

    @Test public void testRollMethod() {
        assertArrayEquals(new int[]{}, Library.roll(0));
        assertEquals(new int[3].length, Library.roll(3).length);

    }

    @Test public void testContainsDuplicatesTest() {
        assertFalse(Library.containsDuplicates(new int[0]));
        assertTrue(Library.containsDuplicates(new int[] {2, 5, 6, 7, 3, 6}));
        assertFalse(Library.containsDuplicates(new int[] {8, 2, 4, 5, 0, 1, 3}));
        assertTrue(Library.containsDuplicates(new int[] {2, 1, 7, 6, 6}));
    }

    @Test public void testCalculateAvg() {
        assertEquals(5, Library.calculateAvg(new int[] {5, 5}), 0f );
        assertEquals(0, Library.calculateAvg(new int[] {}), 0.0f );
        assertEquals(4.24f, Library.calculateAvg(new int[] {2, 5, 7, 3}), 0.1f );
        assertEquals(4.625f, Library.calculateAvg(new int[] {2, 5, 7, 3, 3, 2, 7, 8}), 0.1f );
    }

    @Test public void testCalcArrayofArrayAvgTest() {
        assertArrayEquals(new int[]{55, 54, 60, 53, 59, 57, 61}, Library.calcArrayofArrayAvg(new int[][] {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        }));
    }

    @Test public void testAnalyzeWeatherData() {
        assertEquals("High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69", Library.analyzeWeatherData());
    }

    @Test public void testTallyElection() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        assertEquals("Bush received the most votes!", Library.tallyElection(votes));
    }

}
