/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

import static java.lang.Math.random;

public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }


    public static int[] roll(int n) {
        int[] results = new int[n];
//        int[] dice = new int[] {1, 2, 3, 4, 5, 6};
        for (int i = 0; i < results.length; i++) {
            results[i] = (int) (Math.random() * 6) + 1;
        }
        System.out.println(Arrays.toString(results));
        return results;
    }

    public static boolean containsDuplicates(int[] input) {
        boolean isDuplicate = false;
        if (input.length > 0) {
            aa:
            for (int i = 0; i < input.length - 1; i++) {
                bb:
                for (int x = i + 1; x < input.length; x++) {
                    if (input[i] == input[x]) {
                        isDuplicate = true;
                        break aa;
                    }
                }
            }
        }
        return isDuplicate;
    }

    public static float calculateAvg(int[] input) {
        float avg = 0f;
        for (int i = 0; i < input.length; i++) {
            avg += input[i];
        }
        if (input.length > 0) {
            avg = avg / input.length;
        }
//        System.out.println(avg);
        return avg;
    }

    public static int[] calcArrayofArrayAvg(int[][] input) {
        float[] avgs = new float[input.length];
        int index = 0;
        //calculate averages for each array and insert into avgs[].
        for (int i = 0; i < avgs.length; i++) {
            avgs[i] = calculateAvg(input[i]);
        }
        System.out.println(Arrays.toString(avgs));
        //find index position of array with lowest average.
        for (int x = 0; x < avgs.length - 1; x++) {
            if (avgs[x+1] < avgs[x]) {
                index = x + 1;
            }
        }
        return input[index];
    }

}
